### ISSUE TITLE
编译了下安卓10 然后运行闪退了

### ISSUE THREAD

**Issue by homuraLan** [xfirefly/AD_Client#5]
如题，
```
    compileSdkVersion 29

    flavorDimensions "default"

    defaultConfig {
        applicationId "com.bluberry.adclient"
        minSdkVersion 29
        targetSdkVersion 32
        versionCode 1
        versionName "1.0"

    }
.......
    productFlavors {
        arm {
            ndk {
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
        }
    }
```
一部分错误日志
```
05-25 22:23:06.782  6410  6755 E AndroidRuntime: Process: com.bluberry.adclient, PID: 6410
05-25 22:23:06.782  6410  6755 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
05-25 22:23:06.782  6410  6755 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1239)
05-25 22:23:06.782  6410  6755 E AndroidRuntime: 	at com.bluberry.adclient.App.b(Unknown Source:14)
05-25 22:23:06.782  6410  6755 E AndroidRuntime: 	at com.bluberry.adclient.c$a.run(Unknown Source:30)
05-25 22:23:06.782  6410  6755 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:929)
05-25 22:23:10.853  6926  7505 E AndroidRuntime: FATAL EXCEPTION: Thread-3
05-25 22:23:10.853  6926  7505 E AndroidRuntime: Process: com.bluberry.adclient, PID: 6926
05-25 22:23:10.853  6926  7505 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
05-25 22:23:10.853  6926  7505 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1239)
05-25 22:23:10.853  6926  7505 E AndroidRuntime: 	at 
```
这是完整的日志，希望能得到一些解答，我试了好久
https://github.com/Sincejunly/Sincejunly/blob/main/error.log

**Comment by homuraLan** [comment]
废了一会时间，把所有依赖都更新到最新，还是闪退，只能说爱过
